title: Gator Notes
description: A minimalist approach to KPI's
theme: just-the-docs

url: https://gatornotes.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
